// Generated by Selenium IDE
const { Builder, By, Key, until, promise } = require("selenium-webdriver");
const assert = require("assert");

// Cenários Negativos - Caso de teste 3
describe("campos-obrigatorios", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("campos-obrigatorios", async function () {
    await driver.get("http://automationpractice.com/index.php");
    await driver.manage().window().setRect({ width: 1864, height: 911 });
    await driver.findElement(By.linkText("Sign in")).click();
    await driver.findElement(By.id("email_create")).click();
    await driver
      .findElement(By.id("email_create"))
      .sendKeys("leonardo.santana@aln.senaicimatec.edu.br");

    await driver.findElement(By.id("SubmitCreate")).click();

    await driver.wait(until.elementLocated(By.id("submitAccount")), 30000);

    await driver.findElement(By.id("submitAccount")).click();

    var errorElement1 = await driver
      .findElement(By.css(".inline-infos"))
      .getText();

    assert.equal(errorElement1, "*");
  });

  this.timeout(500000000);
});
