// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

// Cenários Positivos - Caso de teste 6
describe("compra-produto", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("compra-produto", async function () {
    // await driver.get("http://automationpractice.com/index.php");
    await driver.get(
      "http://automationpractice.com/index.php?id_category=5&controller=category"
    );
    await driver.manage().window().setRect({ width: 917, height: 891 });
    // await driver.findElement(By.linkText("T-shirts")).click();
    await driver.findElement(By.css(".lnk_view > span")).click();
    await driver.findElement(By.css(".button-plus > span")).click();

    await driver.wait(until.elementLocated(By.id("group_1")), 30000);

    {
      const dropdown = await driver.findElement(By.id("group_1"));
      await dropdown.findElement(By.xpath("//option[. = 'L']")).click();
    }
    {
      const element = await driver.findElement(By.id("group_1"));
      await driver
        .actions({ bridge: true })
        .move(element)
        // .clickAndHold()
        .perform();
    }
    {
      const element = await driver.findElement(By.id("group_1"));
      await driver.actions({ bridge: true }).move(element).perform();
    }
    {
      const element = await driver.findElement(By.id("group_1"));
      await driver.actions({ bridge: true }).move(element).release().perform();
    }
    await driver.findElement(By.id("color_14")).click();
    await driver.findElement(By.css(".exclusive > span")).click();
    await driver.findElement(By.css(".button-medium > span")).click();
    await driver.findElement(By.css(".standard-checkout > span")).click();
    await driver.findElement(By.css(".button:nth-child(4) > span")).click();
    await driver.findElement(By.css(".standard-checkout > span")).click();
    await driver.findElement(By.css(".fancybox-item")).click();
    await driver.findElement(By.css(".order_carrier_content")).click();
    await driver.findElement(By.id("cgv")).click();
    await driver.findElement(By.css(".standard-checkout > span")).click();
    await driver
      .findElement(
        By.linkText("Pay by bank wire (order processing will be longer)")
      )
      .click();
    await driver.findElement(By.css("#cart_navigation span")).click();
    await driver.findElement(By.css(".account > span")).click();
    await driver
      .findElement(
        By.css(
          ".col-xs-12:nth-child(1) > .myaccount-link-list > li:nth-child(1) span"
        )
      )
      .click();
  });
});
