// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

// Cenários Negativos - Caso de teste 2
describe("email-invalido", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("email-invalido", async function () {
    await driver.get("http://automationpractice.com/index.php");
    await driver.manage().window().setRect({ width: 1864, height: 911 });
    await driver.findElement(By.linkText("Sign in")).click();
    await driver.findElement(By.id("email")).click();
    await driver.findElement(By.id("email")).sendKeys("testtest");
    await driver.findElement(By.css("#SubmitLogin > span")).click();

    var errorMessage = await driver
      .findElement(By.className("alert-danger"))
      .getText();
    assert.equal(errorMessage, "Endereço de e-mail inválido");
  });
});
